language: python

python:
  - "3.6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - sudo apt-get update
  - sudo apt-get install libpulse-mainloop-glib0
  - sudo apt-get install pulseaudio
  - pip install -r requirements.txt

script:
  - python -m unittest

notifications:
    email: false
